//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopPlatform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopPlatform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=85.239.35.30;Database=master;User=sa;Password=12345Aa-;.
        /// </summary>
        internal static string MSSQL_DatabaseConnectionString {
            get {
                return ResourceManager.GetString("MSSQL_DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=shopdb.db;.
        /// </summary>
        internal static string SQlite_DatabaseConnectionString {
            get {
                return ResourceManager.GetString("SQlite_DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopPlatformUsers.
        /// </summary>
        internal static string TokenAudience {
            get {
                return ResourceManager.GetString("TokenAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopPlatformAuthorityServer.
        /// </summary>
        internal static string TokenIssuer {
            get {
                return ResourceManager.GetString("TokenIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e&quot;t(t7ALs)[Wiif&lt;VOY9NRm[c*v/4-4c26Sdy&lt;b/5}.=A_Vv-%&amp;IA3?$)q43Q4).
        /// </summary>
        internal static string TokenSecurityKey {
            get {
                return ResourceManager.GetString("TokenSecurityKey", resourceCulture);
            }
        }
    }
}
